### ISSUE TITLE
Indexing in the mini batch preparation

### ISSUE THREAD

**Issue by Xi-HHHM** [gdy-scu/FlightBERT_PP#2]
Hi, 

Is the indexing in https://github.com/gdy-scu/FlightBERT_PP/blob/main/dataloader.py#L154 correct?

```python
for step in range(0, self.configs.inp_seq_len + self.configs.horizon):
    t_lon.append(self.convert_tar((raw_seq_lon[step], raw_seq_lon[step - 1]), 'lon'))
``` 

If the `step` starts with 0, then the first element of the `t_lon` will be `raw_seq_lon[0] - raw_seq_lon[-1]`, i.e. subtracting the last element from the first element of `raw_seq_lon`. If it is correct, can you please clarify a little bit? Thank you.

**Comment by gdy-scu** [comment]
Thank you for your comment. the raw_seq_lon[0] - raw_seq_lon[-1] will be reset to 0 by lines 272 to 273:
        if len(bin) > self.target_size[type]:
            bin_list = [0] * (self.target_size[type])
Thus, it is Ok in our dataset, which is just like a zero padding of the differential BE representation for the first timestamp.  
We have updated the code accordingly for better understanding.
